export { default as PortalHomepage } from './porttal-homepage/PortalHomepage'
export { default as PlatHomepage } from './plat-homepage/PlatHomepage'
export { default as NewsList } from './news-list/NewsList'
export { default as PublicInfo } from './public-info/PublicInfo'
export { default as PublicInfoVerify } from './public-info-verify/PublicInfoVerify'
export { default as NewsListAdd } from './news-list/news-list-add/NewsListAdd'
