export { default as Page } from './page'
export { default as Align } from './align'
export { default as UploadFile } from './uploadFile'
export { default as MenuItemsCreater } from './menu-items-creater'
export { default as LabelIcon } from './label-icon'
